### ISSUE TITLE
Update github action to check if outputs already exist

### ISSUE THREAD

**Issue by AlexAxthelm** [RMI-PACTA/workflow.prepare.pacta.indices#103]
Runnning index prep is a long process that's part of the current build process for `workflow.transition.monitor`, and will probably be for `workflow.pacta.webapp` as well.

Given that the indices don't actually change that much, it would make sense to do a check if the process needs to actually run, or if we can bypass it, and return the previous results instead.

My general thinking is to construct a hash based on:
* all the `pacta-data`,
* files from this repo
* `benchmark_inputs` files
* docker image (SHA)

and use that as a versioning key, and then we can check if the appropriate files exist in the blob store/AFS

so it would look something like:

```yml
# Download all the files from AZ
# Pull the Base image

- run: |
  hash=some_magic_function(all those inputs)
  echo "hash=$hash" >> "$GITHUB_OUTPUT"

- name: check if file exists on AZ
  run: |
    response=$(az storage blob exists --blog-url "$CONTAINER_URL/$hash/foo.rds" )
    parsed_response="$(jq '.some_filter')" >> "$GITHUB_OUTPUT"

- if: ${{ parsed_response }}
  # early return of the Blob URL

- if: ${{ parsed_response }}
  #run the rest of the process normally
```

cc @jdhoffa @cjyetman, Do I have the hashkeys right, or am I missing something?
